<!doctype html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title><?= $this->title ?></title>
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/favicon.ico" rel="icon shortcut" >
        <?= $this->headMeta(); ?>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <?= $this->headLink(); ?>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body role="document">
        <?= $this->render("admin/menu.phtml") ?>
        <div class="container-fluid">
            <!--<div class="row">
            </div>-->
            <div class="row" style="margin-top: 10px">
                <div class="col-md-12">                    
                    <?= $this->layout()->content; ?>
                </div>
            </div>
            <div class="row">
                <?= $this->render("admin/footer.phtml") ?>
            </div>
        </div>
    </body>
    <?= $this->headScript() ?>
</html>