<!-- Static navbar -->
<div style="margin-left: 20px">
  <a href="/admin"><img src="/images/simar_logo.png" style="width: 250px; float: left; margin-right: 10px"></a> <p style="line-height: 30px; margin: 0; font-size: 14px">Administrador de metadatos del SIMAR</p>
</div>
<div class="clearfix"></div>
<nav class="navbar navbar-default navbar-blue">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a href="/admin" class="navbar-brand">
        <img src="/images/simar.png" style="width: 100px; float: left"> | </a>-->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Acervo de imágenes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/index/satmo">SATMO</a></li>
            <li><a href="/admin/index/satcoral">SATcoral</a></li>
          </ul>
        </li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Metadatos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/index/categorias">Categorías</a></li>
            <li><a href="/admin/index/grupos">Grupos</a></li>
            <!--<li><a href="/admin/index/productos">Productos</a></li>-->
            <li class="dropdown-submenu">
              <a href="/admin/index/productos">Productos</a>
              <ul class="dropdown-menu">
                <li><a href="#">NSST</a></li>
                <li><a href="#">W-NSST</a></li>
                <li class="dropdown-submenu">
                  <a href="/admin/index/productos">Información vectorial</a>
                  <ul class="dropdown-menu">
                    <li><a href="/admin/index/poligonales">ANP regionales marinas</a></li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Información vectorial <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">ANP México</a></li>
            <li><a href="/admin/index/poligonales">ANP regionales</a></li>
          </ul>
        </li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bases de datos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Resiliencia</a></li>
            <li><a href="#">SNIB</a></li>
            <li><a href="/admin/index/satmo">SATMO</a></li>
            <li><a href="/admin/index/satcoral">SATcoral</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bitacora <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/index/bitacora">Log del servidor</a></li>
            <li><a href="/admin/index/calendario">Calendario</a></li>
            <li><a href="/admin/index/produccion">Producción</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="/profiles/users/profile.jpg" alt=""> Admin
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Perfil</a></li>
            <li><a href="javascript:;" id="logout" title="Salir" onclick="javascript:logout();"><i class="fa fa-sign-out pull-right"></i> Salir</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>