<!-- Static navbar -->
<nav class="navbar navbar-default navbar-blue">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin">SIMAR | Web Panel</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="/admin">Acervo de imágenes</a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Acervo de imágenes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">SATMO</a></li>
            <li><a href="#">SATcoral</a></li>
          </ul>
        </li>
        <li><a href="/admin/index/categorias">Metadata</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Información vectorial <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">ANP México</a></li>
            <li><a href="/admin/index/poligonales">ANP regionales</a></li>
          </ul>
        </li>
        <li><a href="/admin/index/bitacora">Bitacora</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="/profiles/users/profile.jpg" alt=""> Admin
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Perfil</a></li>
            <li><a href="javascript:;" id="logout" title="Salir" onclick="javascript:logout();"><i class="fa fa-sign-out pull-right"></i> Salir</a></li>
          </ul>
        </li>
        <!--<li>
            <a><i class="fas fa-sign-out-alt" style="cursor: pointer" id="logout" title="Salir" onclick="javascript:logout();"></i></a></li>-->
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>