<h4>Bitacora</h4>

<div class="row">
  <div class="col-lg-6">
    <div id="table-results" style="min-height: 400px">
        <i class="fas fa-sync" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="update" title="Actualizar"></i>
        <i class="fas fa-table" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="download-report" title="Descargar tabla en Excel"></i>
        <label>Elementos por página: </label>
        <select id="table-results-selector">
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
        </select>
        <br>
        <br>
        <table class="table table-striped table-bordered table-hover simar-table" id="results">
            <thead>
                <tr>
                    <th>Archivo</th>
                    <th style="width: 200px">Fecha</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>  
  </div>
  <div class="col-lg-6">
    <h4 style="margin-bottom: 14px">Contenido</h4>
    <textarea id="content" style="width: 100%; height: 300px; font-size: 0.8em"></textarea>  
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
      <div id="calendar"></div>
      <br>
      <br>
  </div>
  <div class="col-lg-6">
    <iframe src="/admin/get/command" style="height:300px;width:100%; border: 1px #fff solid"></iframe> 
  </div>
</div>