<h4>Acervo de imágenes</h4>

<div id="table-results" style="min-height: 400px">
    <i class="fas fa-sync" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="update" title="Actualizar"></i>
    <i class="fas fa-table" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="download-report" title="Descargar tabla en Excel"></i>
    <label>Elementos por página: </label>
    <select id="table-results-selector">
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
    <label>Tipo de producto: </label>
    <select id="table-results-type">
        <option value="">---</option>
        <option value="day">GHRSST NSST</option>
        <option value="w-nsst">SATmo W-NSST</option>
        <option value="w-nsst-a">SATmo W-NSST-A</option>
        <option value="w-nsst-c">SATmo W-NSST-C</option>
        <option value="m-nsst">SATmo M-NSST</option>
        <option value="m-nsst-a">SATmo M-NSST-A</option>
        <option value="m-nsst-c">SATmo M-NSST-C</option>
        <option value="wy-nsst">SATcoral WY-NSST</option>
        <option value="whs">SATcoral WHS</option>
        <option value="dhw">SATcoral DHW</option>
        <option value="sba">SATcoral SBA</option>
        <option value="noaa-m-nsst-c">NOAA M-NSST-C</option>
        <option value="noaa-mxm-nsst-c">NOAA MxM-NSST-C</option>
    </select>
    <label>Año: </label>
    <select id="table-results-year">
        <option value="">---</option>
    </select>
    <label>Inicio: </label> <input type="text" id="table-results-dateini" style="width: 80px" value="" />
    <label>Fin: </label> <input type="text" id="table-results-dateend" style="width: 80px" value="" />
    <div>
        <label>Buscar: </label> <input type="text" id="table-results-search" style="width: 450px"/><button id="search">Buscar</button>
    </div>

    <br>
    <br>
    <table class="table table-striped table-bordered table-hover simar-table" id="results">
        <thead>
            <tr>
                <th>Rid</th>
                <th>Año</th>
                <th>Mes</th>
                <th>Semana</th>
                <th>Juliano</th>
                <th>Composición</th>
                <th>Sensor</th>
                <th>Producto</th>
                <th>Archivo</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div id="table-results-info"></div>
    <div id="table-results-paginator"></div>
</div>