<h4>Acervo de imágenes</h4>

<div id="table-results" style="min-height: 400px">
    <label>Elementos por página: </label>
    <select id="table-results-selector">
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
    <label>Tipo de producto: </label>
    <select id="table-results-type">
        <option value="">---</option>
        <option value="day">NSST</option>
        <option value="w-nsst">W-NSST</option>
        <option value="m-nsst">M-NSST</option>
        <option value="whs">WHS</option>
        <option value="dhw">DHW</option>
        <option value="sba">SBA</option>
    </select>
    <label>Año: </label>
    <select id="table-results-year">
        <option value="">---</option>
    </select>
    <label>Buscar: </label> <input type="text" id="table-results-serach" />
    <a href="javascript:void(0)" id="download-report" style="float: right">Descargar reporte</a>
    <br>
    <br>
    <table class="table table-striped table-bordered table-hover simar-table" id="results">
        <thead>
            <tr>
                <th>Rid</th>
                <th>Año</th>
                <th>Mes</th>
                <th>Semana</th>
                <th>Juliano</th>
                <th>Composición</th>
                <th>Sensor</th>
                <th>Producto</th>
                <th>Archivo</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div id="table-results-info"></div>
    <div id="table-results-paginator"></div>
</div>