<h4>Bitacora de transmisiones</h4>
<table class="table table-striped table-bordered table-hover" id="datatable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Tipo</th>
            <th>Solicitud</th>
            <th>Fecha</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->data) && !empty($this->data)) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td style="width: 80px"><?= $item["id"] ?></td>
                    <td style="width: 90px">
                        <?php if ($item["externo"]) { ?>
                            <span class="glyphicon glyphicon-arrow-left"></span>
                        <?php } else { ?>
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        <?php } ?>
                    </td>
                    <td><?= $item["solicitud"] ?></td>
                    <td style="width: 150px"><?= $item["creado"] ?></td>
                </tr>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>