<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Producción</h5>

<div class="row">
  <div class="col-lg-12">
      <br>
      <form>
        <div class="form-group">
          <label for="processType">Tipo de proceso:</label>
          <select class="form-control" id="processType">
            <option value="">---</option>
            <option value="1">Descarga (GHRSST)</option>
            <option value="2">Procesamiento SATMO</option>
            <option value="3">Procesamiento SATcoral</option>
            <option value="4">Extras (PNG y KMZ)</option>
          </select>
        </div>
        <div class="form-group">
          <label for="dateIni">Fecha:</label>
          <input type="text" class="form-control" id="dateIni">
        </div>
      </form>
      <button id="run" class="btn btn-success">Ejecutar</button>
      <br>
      <br>
      <textarea id="commands" style="width: 100%; height: 300px; font-size: 0.8em"></textarea>
  </div>
</div>