<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Metadatos <i class="fas fa-angle-double-right"></i> Productos</h5>

<div id="table-results" style="min-height: 400px">
    <i class="fas fa-sync" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="update" title="Actualizar"></i>
    <i class="fas fa-table" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="download-report" title="Descargar tabla en Excel"></i>
    <label>Elementos por página: </label>
    <select id="table-results-selector">
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
    <div>
        <label>Buscar: </label> <input type="text" id="table-results-search" style="width: 250px"/><button id="search">Buscar</button>
    </div>
    <br>
    <table class="table table-striped table-bordered table-hover simar-table" id="results">
        <thead>
            <tr>
                <th>Rid</th>
                <th>Nombre</th>
                <th>Abreviación</th>
                <th>Nombre inglés</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div id="table-results-info"></div>
    <div id="table-results-paginator"></div>
</div>