<!--<h4><strong>Categoría</strong>: <?= $this->name ?></h4>-->
<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Metadatos <i class="fas fa-angle-double-right"></i> Grupos</h5>

<form id="form">
    <input type="hidden" id="id" name="id" value="<?= $this->id ?>" />
    <table class="table table-striped table-bordered table-hover simar-table">
        <thead>
            <tr>
                <th style="width: 200px">Parámetro</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Nombre:</td>
                <td><input id="name" name="name" style="width: 550px" value="<?= $this->name ?>" /></td>
            </tr>
            <tr>
                <td>Abreviación:</td>
                <td><input id="abbreviation" name="abbreviation" style="width: 550px" value="<?= $this->abbreviation ?>" /></td>
            </tr>
            <tr>
                <td>Nombre principal:</td>
                <td><input id="main_name" name="main_name" style="width: 550px" value="<?= $this->main_name ?>" /></td>
            </tr>
            <tr>
                <td>Nombre inglés:</td>
                <td><input id="english_name" name="english_name" style="width: 550px" value="<?= $this->english_name ?>" /></td>
            </tr>
            <tr>
                <td>Orden:</td>
                <td><input id="order" name="order" style="width: 550px" value="<?= $this->order ?>" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <button type="submit" id="submit" class="btn btn-primary pull-right">
                        <i class="far fa-save"></i> Guardar
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<h4>Metadata de grupo</h4>

<div id="editor">
    <div id='edit'>
        <?= $this->description ?>
    </div>
    <br>
</div>

<a class="btn btn-success" href="/admin/index/grupos">
    <i class="fas fa-angle-double-left"></i> Regresar</a>

<button class="btn btn-primary pull-right" id="saveButton">
    <i class="far fa-save"></i> Guardar</button>
