<h4>Acervo de imágenes</h4>

<div id="table-results" style="min-height: 400px">
    <i class="fas fa-sync" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="update" title="Actualizar"></i>
    <i class="fas fa-table" style="color: white; float: right; margin: 0 5px; cursor: pointer" id="download-report" title="Descargar tabla en Excel"></i>
    <label>Elementos por página: </label>
    <select id="table-results-selector">
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
    <div>
        <label>Buscar: </label> <input type="text" id="table-results-search" style="width: 250px"/><button id="search">Buscar</button>
    </div>
    <br>
    <br>
    <table class="table table-striped table-bordered table-hover simar-table" id="results">
        <thead>
            <tr>
                <th>Rid</th>
                <th>Año</th>
                <th>Semana</th>
                <th>Clase 1</th>
                <th>Clase 2</th>
                <th>Clase 3</th>
                <th>Clase 4</th>
                <th>Clase 5</th>
                <th>% Clase 1</th>
                <th>% Clase 2</th>
                <th>% Clase 3</th>
                <th>% Clase 4</th>
                <th>% Clase 5</th>
                <th>Total</th>
                <th>Nivel de alerta (R-SBA)</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div id="table-results-info"></div>
    <div id="table-results-paginator"></div>
</div>

<a class="btn btn-success" href="/admin/index/poligonales">Regresar</a>