<?php if (isset($this->paginator)) { ?>
    <?php foreach ($this->paginator as $item) { ?>
        <tr>
            <td>
                <a href="/admin/index/ver-categoria?id=<?= $item["id"] ?>"><?= $item["id"] ?></a>
            </td>
            <td><?= $item["name"] ?></td>
            <td><?= $item["abbreviation"] ?></td>
            <td><?= $item["main_name"] ?></td>
            <td><?= $item["english_name"] ?></td>
            <td><?= $item["order"] ?></td>
            <td><?= date("d/m/Y", strtotime($item["created_at"])) ?></td>
        </tr>
    <?php } ?>
<?php } else { ?>
    <tr>
        <td colspan="7">
            <em>No hay categorias</em>
        </td>
    </tr>
<?php } ?>