<?php if (isset($this->paginator)) { ?>
    <?php foreach ($this->paginator as $item) { ?>
        <tr>
            <td>
                <a href="/admin/resiliencia/ver-institucion?id=<?= $item["rid"] ?>">
                    <i class="fas fa-folder-open"></i></a>
            </td>
            <td>
                <?= $item["nombre"] ?></td>
            </td>
            <td><?= date("d/m/Y", strtotime($item["creado"])) ?></td>
        </tr>
    <?php } ?>
<?php } else { ?>
    <tr>
        <td colspan="3">
            <em>No hay instituciones</em>
        </td>
    </tr>
<?php } ?>