<table class="table table-striped table-bordered table-hover" id="datatable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Razón Social</th>
            <th>RFC</th>
            <th>VUCEM</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->data) && !empty($this->data)) { ?>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td><?= $item["id"] ?></td>
                    <td><?= $item["razonSocial"] ?></td>
                    <td><?= $item["identificador"] ?></td>
                    <td><?= ($item["sello"]) ? "Si" : "No" ?></td>
                    <td style="text-align: right">
                        <div class="btn-group btn-group-sm" role="group" aria-label="">
                            <a class="btn btn-default btn-sm btn-primary" href="/administrador/clientes/direccion?id=<?= $item["id"] ?>">Dirección</a>
                            <a class="btn btn-default btn-sm btn-warning" href="/administrador/clientes/aduanas?id=<?= $item["id"] ?>">Aduanas</a>
                            <a class="btn btn-default btn-sm btn-success" href="/administrador/clientes/sellos?id=<?= $item["id"] ?>">Sello (FIEL)</a>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>
<a class="btn btn-info pull-right" href="/administrador/clientes/alta-cliente" role="button">Alta cliente</a>