<div class="row">
    <div class="col-md-6">
        <!--        <div class="radio">
                    <label>
                        <input type="radio" name="opciones" id="customer" value="1">
                        Usar sello de cliente
                    </label>
                </div>-->
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Key</th>
                    <th>Creado</th>
                    <th>Default</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->data) && !empty($this->data)) { ?>
                    <?php foreach ($this->data as $item) { ?>
                        <tr>
                            <td><?= $item["archivoKey"] ?></td>
                            <td><?= $item["creado"] ?></td>
                            <td>
                                <input type="radio" name="default" value="<?= $item["id"] ?>"<?= ($item["default"] == 1) ? " checked=\"true\"" : "" ?>>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="3">
                            <em>El cliente no tiene sellos en el sistema.</em>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <!--        <div class="radio">
                    <label>
                        <input type="radio" name="opciones" id="agent" value="2">
                        Usar sello de agente aduanal
                    </label>
                </div>-->
        <table class="table table-striped table-bordered table-hover">
            <tbody>
                <tr>
                    <th>&nbsp;</th>
                    <th>Patente</th>
                    <th>Nombre</th>
                </tr>
            </tbody>
            <?php if (isset($this->agentes) && !empty($this->agentes)) { ?>
                <?php foreach ($this->agentes as $item) { ?>
                    <tr>
                        <td>
                            <input type="checkbox" class="useAgent" value="<?= $item["id"] ?>" <?= isset($item["asignado"]) ? " checked=\"true\"" : "" ?>>
                        </td>
                        <td><?= $item["patente"] ?></td>
                        <td><?= $item["razonSocial"] ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="3"><em>No existen agentes aduanales en el sistema.</em></td>
                </tr>
            <?php } ?>
        </table>
        <table class="table table-striped table-bordered table-hover">
            <tbody>
                <tr>
                    <th>&nbsp;</th>
                    <th>RFC</th>
                </tr>
            </tbody>
            <?php if (isset($this->rfcs) && !empty($this->rfcs)) { ?>
                <?php foreach ($this->rfcs as $item) { ?>
                    <tr>
                        <td>
                            &nbsp;
                        </td>
                        <td><?= $item["rfc"] ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="2"><em>No tiene RFC's de consulta.</em></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
<div class="row" style="margin-bottom: 5px"></div>
<div class="row">
    <div class="col-md-12">
        <form action="<?= $this->form->getAction() ?>" method="post" id="fiel">
            <?= $this->form->idCliente ?>
            <?= $this->form->password ?>
            <?= $this->form->webservice ?>
            <div class="form-group">
                <label for="keyFile">ARCHIVO KEY:</label>
                <input type="file" id="keyFile" name="keyFile">
                <p class="help-block">Seleccionar el archivo .key</p>
            </div>
            <div class="form-group">
                <label for="cerFile">ARCHIVO CER:</label>
                <input type="file" id="cerFile" name="cerFile">
                <p class="help-block">Seleccionar el archivo .cer</p>
            </div>
            <div class="form-group">
                <label for="cifrado">CIFRADO DE SELLO:</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="cifrado" id="optionsRadios1" value="1" checked>
                        Normal
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="cifrado" id="optionsRadios2" value="2">
                        256 (Sellos 2015)
                    </label>
                </div>
            </div>
            <button class="btn btn-primary pull-right" type="submit" id="submit">Agregar Sello</button>
        </form>
        <a class="btn btn-warning" href="/administrador/clientes/index" role="button">«&nbsp;Regresar</a>
    </div>
</div>