<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Metadatos <i class="fas fa-angle-double-right"></i> Productos</h5>

<form id="form">
    <input type="hidden" id="id" name="id" value="<?= $this->id ?>" />
    <table class="table table-striped table-bordered table-hover simar-table">
        <thead>
            <tr>
                <th style="width: 200px">Parámetro</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Composición:</td>
                <td>
                    <input class="form-control" id="composition" name="composition" readonly="true"/></td>
            </tr>
            <tr>
                <td>Titulo español:</td>
                <td>
                    <input class="form-control" id="spanish_title" name="spanish_title" /></td>
            </tr>
            <tr>
                <td>Titulo inglés:</td>
                <td>
                    <input class="form-control" id="title" name="title" /></td>
            </tr>
            <tr>
                <td>Subtitulo:</td>
                <td>
                    <input class="form-control" id="subtitle" name="subtitle" /></td>
            </tr>
            <tr>
                <td>Miniatura:</td>
                <td>
                    <input class="form-control" id="thumb_image" name="thumb_image" /></td>
            </tr>
            <tr>
                <td>Unidades de medida:</td>
                <td>
                    <input class="form-control" id="color_ramp_unit" name="color_ramp_unit" /></td>
            </tr>
            <tr>
                <td>Rampa de color:</td>
                <td>
                    <textarea id="color_ramp" name="color_ramp" class="form-control" rows="10" readonly="true"></textarea>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<h4>Metadata del producto</h4>

<div id="editor">
    <div id='edit'></div>
    <br>    
</div>

<a class="btn btn-success" href="javascript:void(0)" onclick="goBack()">
    <i class="fas fa-angle-double-left"></i> Regresar</a>

