<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Metadatos <i class="fas fa-angle-double-right"></i> Categorías</h5>

<form id="form">
    <input type="hidden" id="id" name="id" value="<?= $this->id ?>" />
    <table class="table table-striped table-bordered table-hover simar-table">
        <thead>
            <tr>
                <th style="width: 200px">Parámetro</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Nombre:</td>
                <td>
                    <input class="form-control" id="name" name="name" value="<?= $this->name ?>" />
                </td>
            </tr>
            <tr>
                <td>Abreviación:</td>
                <td>
                    <input class="form-control" id="abbreviation" name="abbreviation" value="<?= $this->abbreviation ?>" readonly="true" /></td>
            </tr>
            <tr>
                <td>Nombre principal:</td>
                <td>
                    <input class="form-control" id="main_name" name="main_name" value="<?= $this->main_name ?>" /></td>
            </tr>
            <tr>
                <td>Nombre inglés:</td>
                <td>
                    <input class="form-control" id="english_name" name="english_name" value="<?= $this->english_name ?>" /></td>
            </tr>
            <tr>
                <td>Orden:</td>
                <td>
                    <input class="form-control" id="order" name="order" value="<?= $this->order ?>" readonly="true" /></td>
            </tr>
        </tbody>
    </table>
</form>

<h4>Metadata de categoría</h4>

<div id="editor">
    <div id='edit'>
        <?= $this->description ?>
    </div>
    <br>
</div>

<a class="btn btn-success" href="/admin/index/categorias">
    <i class="fas fa-angle-double-left"></i> Regresar</a>
