
<link rel="stylesheet" href="/js/common/leaflet/leaflet.css" />
<script src="/js/common/leaflet/leaflet.js"></script>
<script src="/js/common/leaflet-tilelayer-wmts.js"></script>
<script src="/js/common/jquery-1.12.4.min.js"></script>

<table class="table table-striped table-bordered table-hover simar-table" id="results">
    <thead>
        <tr>
            <th style="width: 200px">Parámetro</th>
            <th>Valor</th>
            <th>Imagen</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Nombre imagen:</td>
            <td><input id="filename" style="width: 550px" value="" /></td>
            <td rowspan="18" style="width: 320px">
                <!--<img id="thumbnail" style="width: 300px" />-->
                <div id="map" style="width: 100%; height: 300px; margin-bottom: 5px"></div>
                <a class="btn btn-sm btn-primary" href="javascript:void(0)" id="downloadlink" target="_blank" style="display: none" title="Descargar GeoTiff"><i class="fas fa-download"></i> GTiff</a>
                <a class="btn btn-sm btn-primary" href="javascript:void(0)" id="viewOnMap" target="_blank" style="display: none" title="Ver mapa en pantalla"><i class="fas fa-map"></i></a>
                <a class="btn btn-sm btn-primary" href="javascript:void(0)" id="viewFolder" target="_blank" style="display: none" title="Abrir ubicación del archivo"><i class="fas fa-folder-open"></i></a>
                <a class="btn btn-sm btn-success" href="javascript:void(0)" id="downloadKmz" target="_blank" style="display: none" title="Descargar KMZ"><i class="fas fa-globe"></i></a>
                <a class="btn btn-sm btn-success" href="javascript:void(0)" id="downloadPng" target="_blank" style="display: none" title="Descargar PNG"><i class="fas fa-image"></i></a>
                <script>
                
                    var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'});

                    var map = L.map('map', {
                        center: [0.0, -0.00208952547398],
                        zoom: 6,
                        minZoom: 0,
                        maxZoom: 8,
                        layers: [osm]
                    });
                    
                    var lyr = L.tileLayer('<?= $this->url ?>', 
                        {tms: false, opacity: 1, attribution: ""
                    });
                    var overlaymaps = {
                        "<?= $this->layerName ?>": lyr,
                    }
                    map.addLayer(lyr)

                    var basemaps = {"OpenStreetMap": osm}
                    //L.control.layers(basemaps, overlaymaps, {collapsed: false}).addTo(map);
                    map.fitBounds([[<?= $this->yMin ?>, <?= $this->xMin ?>], [<?= $this->yMax ?>, <?= $this->xMax ?>]]);

                </script>
            </td>
        </tr>

        <tr>
            <td>Año:</td>
            <td><input id="year" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Día:</td>
            <td><input id="day" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Composición:</td>
            <td><input id="composition" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Producto:</td>
            <td><input id="product" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Sensor:</td>
            <td><input id="sensor" style="width: 150px" value="" /></td>
        </tr>


        <tr>
            <td>Valor mínimo:</td>
            <td><input id="min" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Valor máximo:</td>
            <td><input id="max" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Valor promedio:</td>
            <td><input id="mean" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Desviación estándar:</td>
            <td><input id="std_dev" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Resolución de píxel:</td>
            <td><input id="pix_res" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Proyeccíón:</td>
            <td><input id="projection" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Tipo de dato:</td>
            <td><input id="bit_depth" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Valor nulo (no data value):</td>
            <td><input id="no_data" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>X min.:</td>
            <td><input id="x_min" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Y min.:</td>
            <td><input id="y_min" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>X max.:</td>
            <td><input id="x_max" style="width: 150px" value="" /></td>
        </tr>
        <tr>
            <td>Y max.:</td>
            <td><input id="y_max" style="width: 150px" value="" /></td>
        </tr>
    </tbody>
</table>
<div class="metadata" style="display: none"></div>

<a class="btn btn-success" href="javascript:void(0)" onclick="goBack()">
    <i class="fas fa-angle-double-left"></i> Regresar</a>