<?php if(isset($this->data) && !empty($this->data)) { ?>
<table class="table table-striped table-bordered table-hover" id="datatable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Razón Social</th>
            <th>RFC</th>
            <th>Patente</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $item) { ?>
        <tr>
            <td><?= $item["id"] ?></td>
            <td><?= $item["razonSocial"] ?></td>
            <td><?= $item["rfc"] ?></td>
            <td><?= $item["patente"] ?></td>
            <td style="text-align: right">
                <div class="btn-group btn-group-sm" role="group" aria-label="">
                    <a class="btn btn-default btn-sm btn-primary" href="/administrador/agentes/aduanas?id=<?= $item["id"] ?>">Aduanas</a>
                    <a class="btn btn-default btn-sm btn-success" href="/administrador/agentes/sellos?id=<?= $item["id"] ?>">Sello (FIEL)</a>
                </div>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<a class="btn btn-info pull-right" href="/administrador/agentes/alta-agente" role="button">Alta agente</a>
<?php } ?>