<!-- Static navbar -->
<div style="margin-left: 20px">
  <a href="/admin"><img src="/images/simar_logo.png" style="width: 250px; float: left; margin-right: 10px"></a> <p style="line-height: 30px; margin: 0; font-size: 14px">Administrador de metadatos del SIMAR</p>
</div>
<div class="clearfix"></div>
<nav class="navbar navbar-default navbar-blue">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Metadatos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a href="/usuario/index/categorias">Categorías</a>
              <ul class="dropdown-menu">
                <?php if (isset($this->categorias)) { ?>
                  <?php foreach ($this->categorias as $item) { ?>
                    <li><a href="/usuario/index/ver-categoria?id=<?= $item["id"] ?>"><?= filter_var($item["main_name"], FILTER_SANITIZE_STRING) ?></a></li>
                  <?php } ?>
                <?php } ?>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a href="/usuario/index/grupos">Grupos</a>
              <ul class="dropdown-menu">
                <?php if (isset($this->grupos)) { ?>
                  <?php foreach ($this->grupos as $item) { ?>
                    <li><a href="/usuario/index/ver-grupo?id=<?= $item["id"] ?>"><?= filter_var($item["main_name"], FILTER_SANITIZE_STRING) ?></a></li>
                  <?php } ?>
                <?php } ?>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a href="/usuario/index/productos">Productos</a>
              <ul class="dropdown-menu">
                <?php if (isset($this->productos)) { ?>
                  <?php foreach ($this->productos as $item) { ?>
                    <li><a href="/usuario/index/ver-producto-de-categoria?id=<?= $item["id"] ?>"><?= filter_var($item["title"], FILTER_SANITIZE_STRING) ?></a></li>
                  <?php } ?>
                <?php } ?>
              </ul>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bases de datos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a href="/usuario/index/satmo">Resiliencia</a>
              <ul class="dropdown-menu">
                <li><a href="/usuario/resiliencia/instituciones">Instituciones</a></li>
                <li><a href="/usuario/resiliencia/adscripciones">Adscripciones</a></li>
                <li><a href="/usuario/resiliencia/sectores">Sectores</a></li>
                <li><a href="/usuario/resiliencia/grados-academicos">Grados académicos</a></li>
                <li><a href="/usuario/resiliencia/especialistas">Investigadores y especialistas</a></li>
                <li><a href="/usuario/resiliencia/proyectos">Proyectos</a></li>
              </ul>
            </li>
            <li><a href="/usuario/snib/index">SNIB</a></li>
            <li class="dropdown-submenu">
              <a href="/usuario/index/satmo">SATMO</a>
              <ul class="dropdown-menu">
                <li><a href="/admin/index/satmo">Productos satelitales SATMO</a></li>
                <li><a href="/admin/index/satcoral">Productos satelitales SATcoral</a></li>
              </ul>
            </li>
            <li><a href="/usuario/index/satcoral">SATcoral</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="<?= isset($this->profile) ? $this->profile : '/profiles/users/profile-default.jpg' ?>" alt=""> <?= ucfirst($this->username) ?>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Perfil</a></li>
            <li><a href="javascript:;" id="logout" title="Salir" onclick="javascript:logout();"><i class="fa fa-sign-out pull-right"></i> Salir</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>