<!doctype html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title><?= $this->title ?></title>
        <meta name="author" content="SitePoint">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/favicon.ico" rel="icon shortcut" >
        <?= $this->headMeta(); ?>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
        <?= $this->headLink(); ?>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body style="background: url(images/background-01a.jpg); background-repeat: no-repeat; background-size: cover">
        <div class="container-fluid">
            <div class="row">
                <?= $this->layout()->content; ?>
                <?= $this->render("landing/footer.phtml") ?>
            </div>
        </div>
        <?= $this->headScript() ?>
    </body>
</html>