<form method="post" enctype="application/x-www-form-urlencoded" id="form">
    <input type="hidden" value="<?= $this->data["idCliente"] ?>" name="id" id="id" >
    <table class="table">
        <thead>
            <tr>
                <th colspan="2">SELLO</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Identificador:</td>
                <td><?= $this->data["identificador"] ?></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><?= $this->data["pass"] ?></td>
            </tr>
            <tr>
                <td>Password WS:</td>
                <td>
                    <div class="form-group">                    
                        <input type="text" name="ws" id="ws" value="<?= $this->data["ws"] ?>" class="form-control">
                    </div>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <button type="submit" id="submit" class="btn btn-success">Actualizar</button>
                    <button type="submit" id="test" class="btn btn-primary">Probar</button>
                </td>
            </tr>
            <tr>
                <td colspan="2" id="error" style="display: none"></td>
            </tr>
        </tbody>
    </table>
    <a onclick="window.history.back();" class="btn btn-warning">&laquo;&nbsp;Regresar</a>
</form>