
<?php if(isset($this->data) && !empty($this->data)) { ?>
<table class="table table-striped table-bordered table-hover" id="datatable">
    <thead>
        <tr>
            <th>RFC</th>
            <th>Key</th>
            <th>Certificado</th>
            <th>Creado</th>
            <th>Modificado</th>
            <th>&nbsp;</th>
            <th>Respuesta</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $item) { ?>
        <tr>
            <td><?= $item["rfc"] ?></td>
            <td><?= $item["archivoCer"] ?></td>
            <td><?= $item["archivoKey"] ?></td>
            <td><?= $item["creado"] ?></td>
            <td><?= $item["modificado"] ?></td>
            <td>
                <a class="btn btn-default btn-sm btn-success" data="<?= $item["id"] ?>" href="<?= $this->url(array("action" => "editar-sello", "id" => $item["id"])) ?>">Editar sello</a>
            </td>
            <td>
                <div id="result_<?= $item["id"] ?>"></div>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } else { ?>
<p class="bg-danger">
    El sistema no tiene sellos cargados.
</p>
<?php } ?>