<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Base de datos <i class="fas fa-angle-double-right"></i> Resiliencia <i class="fas fa-angle-double-right"></i> Institución</h5>

<form id="form">
    <input type="hidden" id="id" name="id" value="<?= $this->arr['rid'] ?>" />
    <table class="table table-striped table-bordered table-hover simar-table">
        <thead>
            <tr>
                <th style="width: 200px">Parámetro</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Sector:</td>
                <td>
                    </td>
            </tr>
            <tr>
                <td>Nombre:</td>
                <td>
                    <input class="form-control" id="nombre" name="nombre" value="<?= $this->arr['nombre'] ?>" /></td>
            </tr>
            <tr>
                <td>Sitio Web:</td>
                <td>
                    <input class="form-control" id="sitio_web" name="sitio_web" value="<?= $this->arr['sitio_web'] ?>"/></td>
            </tr>
            <tr>
                <td>País:</td>
                <td>
                    <input class="form-control" id="pais" name="pais" value="<?= $this->arr['pais'] ?>" /></td>
            </tr>
        </tbody>
    </table>
</form>

<a class="btn btn-success" href="/usuario/resiliencia/instituciones">Regresar</a>