<form method="post" enctype="application/x-www-form-urlencoded" id="form">
    <?= $this->form->id ?>
    <?= $this->form->username ?>
    <?= $this->form->nombre ?>
    <?= $this->form->email ?>
    <?= $this->form->password ?>
    <?= $this->form->repeat ?>
    <button class="btn btn-primary pull-right" type="submit" id="submit">Guardar</button>
    <a onclick="window.history.back();" class="btn btn-warning">&laquo;&nbsp;Regresar</a>
</form>