<div class="row" style="margin-bottom: 5px"></div>
<?php if (isset($this->data) && !empty($this->data)) { ?>
    <table class="table table-striped table-bordered table-hover table-narrow" id="datatable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Usuario</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $item) { ?>
                <tr>
                    <td style="width: 30px; text-align: center"><?= $item["id"] ?></td>
                    <td style="width: 250px"><?= $item["username"] ?></td>
                    <td style="text-align: right">
                        <a class="btn btn-sm btn-success" href="<?= $this->url(array('action' => 'editar-usuario', 'id' => $item["id"])) ?>" role="button">Editar</a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>
</div>