<link rel="stylesheet" href="/js/common/leaflet/leaflet.css" />
<script src="/js/common/leaflet/leaflet.js"></script>
<script src="/js/common/leaflet-tilelayer-wmts.js"></script>
<script src="/js/common/jquery-1.12.4.min.js"></script>

<h5><i class="fas fa-home"></i> <i class="fas fa-angle-double-right"></i> Base de datos <i class="fas fa-angle-double-right"></i> SNIB <i class="fas fa-angle-double-right"></i> Especimen</h5>

<br>
<h5 style="color: yellow">En construcción</h5>


<table class="table table-striped table-bordered table-hover simar-table">
    <thead>
        <tr>
            <th style="width: 200px">Parámetro</th>
            <th>Valor</th>
            <th>Ubicación</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Url externa:</td>
            <td>
                <a href="<?= $this->arr->urlejemplar ?>" target="_blank"><?= $this->arr->urlejemplar ?></a></td>
            <td rowspan="20" style="width: 320px">
                <div id="map" style="width: 100%; height: 300px; margin-bottom: 5px"></div>
                <script>
                
                    var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'});

                    var map = L.map('map', {
                        center: [<?= $this->arr->latitud ?>, <?= $this->arr->longitud ?>],
                        zoom: 6,
                        minZoom: 0,
                        maxZoom: 8,
                        layers: [osm]
                    });

                    var basemaps = {"OpenStreetMap": osm}

                    var marker = L.marker([<?= $this->arr->latitud ?>, <?= $this->arr->longitud ?>]).addTo(map).bindPopup("<?= $this->arr->grupobio ?><br><?= $this->arr->subgrupobio ?><br><?= $this->arr->familiavalida ?>");
                    

                </script>
            
            </td>
        </tr>
        <tr>
            <td>Grupobio:</td>
            <td>
                <input value="<?= $this->arr->grupobio ?>" /></td>
        </tr>
        <tr>
            <td>Subgrupobio:</td>
            <td>
                <input value="<?= $this->arr->subgrupobio ?>" style="width: 300px"/></td>
        </tr>
        <tr>
            <td>Familiavalida:</td>
            <td>
                <input value="<?= $this->arr->familiavalida ?>" /></td>
        </tr>
        <tr>
            <td>generovalido:</td>
            <td>
                <input value="<?= $this->arr->generovalido ?>" /></td>
        </tr>
        <tr>
            <td>generovalido:</td>
            <td>
                <input value="<?= $this->arr->generovalido ?>" /></td>
        </tr>
        <tr>
            <td>estadomapa:</td>
            <td>
                <input value="<?= $this->arr->estadomapa ?>" /></td>
        </tr>
        <tr>
            <td>municipiomapa:</td>
            <td>
                <input value="<?= $this->arr->municipiomapa ?>" /></td>
        </tr>
        <tr>
            <td>localidad:</td>
            <td>
                <input value="<?= $this->arr->localidad ?>" /></td>
        </tr>
        <tr>
            <td>fechacolecta:</td>
            <td>
                <input value="<?= $this->arr->fechacolecta ?>" /></td>
        </tr>
        <tr>
            <td>generovalido:</td>
            <td>
                <input value="<?= $this->arr->generovalido ?>" /></td>
        </tr>
        <tr>
            <td>fuente:</td>
            <td>
                <input value="<?= $this->arr->fuente ?>" /></td>
        </tr>
        <tr>
            <td>reino:</td>
            <td>
                <input value="<?= $this->arr->reino ?>" /></td>
        </tr>
        <tr>
            <td>phylumdivision:</td>
            <td>
                <input value="<?= $this->arr->phylumdivision ?>" /></td>
        </tr>
        <tr>
            <td>clase:</td>
            <td>
                <input value="<?= $this->arr->clase ?>" /></td>
        </tr>
        <tr>
            <td>orden:</td>
            <td>
                <input value="<?= $this->arr->orden ?>" /></td>
        </tr>
        <tr>
            <td>familia:</td>
            <td>
                <input value="<?= $this->arr->familia ?>" /></td>
        </tr>
        <tr>
            <td>genero:</td>
            <td>
                <input value="<?= $this->arr->genero ?>" /></td>
        </tr>
        <tr>
            <td>especie:</td>
            <td>
                <input value="<?= $this->arr->especie ?>" /></td>
        </tr>
        <tr>
            <td>autor:</td>
            <td>
                <input value="<?= $this->arr->autor ?>" /></td>
        </tr>
    </tbody>
</table>
<a class="btn btn-success" href="/usuario/snib/index">Regresar</a>