<?php if (isset($this->paginator)) { ?>
    <?php foreach ($this->paginator as $item) { ?>
        <tr>
            <td>
                <a href="/usuario/index/ver-grupo?id=<?= $item["id"] ?>">
                    <i class="fas fa-folder-open"></i></a></td>
            <td>
                <a href="/usuario/index/ver-grupo?id=<?= $item["id"] ?>">
                    <?= $item["name"] ?></a></td>
            <td><?= $item["abbreviation"] ?></td>
            <td><?= $item["main_name"] ?></td>
            <td><?= $item["english_name"] ?></td>
            <td><?= $item["order"] ?></td>
            <td><?= date("d/m/Y", strtotime($item["created_at"])) ?></td>
        </tr>
    <?php } ?>
<?php } else { ?>
    <tr>
        <td colspan="7">
            <em>No hay categorias</em>
        </td>
    </tr>
<?php } ?>